{
  "formatVersion": "1.1",
  "component": {
    "group": "tf.ssf.sfort",
    "module": "fscript-shell",
    "version": "3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fscript-shell-3.jar",
          "url": "fscript-shell-3.jar",
          "size": 18521,
          "sha512": "b9031958525740460cec462b9d9a8316f8d07c3d7d7224294ae6a292dbd11048dade41dc0458bf84c464c21032cfa8970a2668a9b907d455345395a24f88f439",
          "sha256": "fbe50d4e7a53111f394942005ef045f842c0fee7b09bf1fd44c9e24ee87a732b",
          "sha1": "1e72b5ef31d859852d530de96de53b31481363d1",
          "md5": "bb36079cabc22893cc7d07a51c6bc9e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fscript-shell-3.jar",
          "url": "fscript-shell-3.jar",
          "size": 18521,
          "sha512": "b9031958525740460cec462b9d9a8316f8d07c3d7d7224294ae6a292dbd11048dade41dc0458bf84c464c21032cfa8970a2668a9b907d455345395a24f88f439",
          "sha256": "fbe50d4e7a53111f394942005ef045f842c0fee7b09bf1fd44c9e24ee87a732b",
          "sha1": "1e72b5ef31d859852d530de96de53b31481363d1",
          "md5": "bb36079cabc22893cc7d07a51c6bc9e5"
        }
      ]
    }
  ]
}
