{
  "formatVersion": "1.1",
  "component": {
    "group": "tf.ssf.sfort",
    "module": "fscript-shell",
    "version": "3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fscript-shell-3.jar",
          "url": "fscript-shell-3.jar",
          "size": 18545,
          "sha512": "64a24071aeae90d2612a132901c99785ae1efa0286df7ffd63ebe5b2917c638d9aebad86086c323deef0b9ef97070d11c9d36b35c94143d92dac0d164d89bc00",
          "sha256": "d7bc38de8d36ac47fc9be05956ca2a036d1f21e8debb6c81dc64f8822d19b54b",
          "sha1": "3a164b5746fcc846c470a8a565356be9d83e6fb7",
          "md5": "e1bffe6c175c191ba2894f33ec0f0962"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fscript-shell-3.jar",
          "url": "fscript-shell-3.jar",
          "size": 18545,
          "sha512": "64a24071aeae90d2612a132901c99785ae1efa0286df7ffd63ebe5b2917c638d9aebad86086c323deef0b9ef97070d11c9d36b35c94143d92dac0d164d89bc00",
          "sha256": "d7bc38de8d36ac47fc9be05956ca2a036d1f21e8debb6c81dc64f8822d19b54b",
          "sha1": "3a164b5746fcc846c470a8a565356be9d83e6fb7",
          "md5": "e1bffe6c175c191ba2894f33ec0f0962"
        }
      ]
    }
  ]
}
