{
  "formatVersion": "1.1",
  "component": {
    "group": "tf.ssf.sfort",
    "module": "fscript",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fscript-2.1.2.jar",
          "url": "fscript-2.1.2.jar",
          "size": 103866,
          "sha512": "3a5b66d4bed6bfad6a1359fade269d4277049234fc6168e9febda128eb55b32b91a4b315f0b650125fcdcfc17f91c1befbdebed3250ae72756079d768a187309",
          "sha256": "b20ad93bbc66d62f6a322518d1ab2b5908ece29e66fff9818a63da9447e20269",
          "sha1": "14aa2768baeea7f9407d278e2c9289b147924ecb",
          "md5": "6f0ec05c54a28a4e374e15d03a801914"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "fscript-2.1.2.jar",
          "url": "fscript-2.1.2.jar",
          "size": 103866,
          "sha512": "3a5b66d4bed6bfad6a1359fade269d4277049234fc6168e9febda128eb55b32b91a4b315f0b650125fcdcfc17f91c1befbdebed3250ae72756079d768a187309",
          "sha256": "b20ad93bbc66d62f6a322518d1ab2b5908ece29e66fff9818a63da9447e20269",
          "sha1": "14aa2768baeea7f9407d278e2c9289b147924ecb",
          "md5": "6f0ec05c54a28a4e374e15d03a801914"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fscript-2.1.2-sources.jar",
          "url": "fscript-2.1.2-sources.jar",
          "size": 42402,
          "sha512": "702548b208b470600b36a7193e01a5e4e31f51b1af9edcb339d60a0b9d90b29557d0adb5d737caed9ba2775138343a17081d5d0ba578f51de3fd958d26427944",
          "sha256": "8985e4591ad3bf59a4177b8b98a31a0cecd9fdd06d321bd7e506e92d4ff738e9",
          "sha1": "1726ea52c810cabceb60cbd4255cdcece9d356c1",
          "md5": "1adbe1dfb59ab89905d3ba9e08178f23"
        }
      ]
    }
  ]
}
