{
  "formatVersion": "1.1",
  "component": {
    "group": "tf.ssf.sfort",
    "module": "fscript",
    "version": "3.1.2-1.16.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fscript-3.1.2-1.16.5.jar",
          "url": "fscript-3.1.2-1.16.5.jar",
          "size": 107796,
          "sha512": "44a14ea7b4e177d8620514ad4155f20769591a327ec14d73a6ad71f6b146c5ab3f90264b0b28dd11bb1410c54c4b359ceb0ad35a56be295681621a44590efba7",
          "sha256": "47bf95c9676fdfbe67f0520c04dfb51c5c4f5ba2ab4a4fa8200f1694b86e1ff5",
          "sha1": "01b0a081929d040f66e5705b9adb6b43dfa70bf2",
          "md5": "46480d0ae3ae044749b924c7bc87be8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "fscript-3.1.2-1.16.5.jar",
          "url": "fscript-3.1.2-1.16.5.jar",
          "size": 107796,
          "sha512": "44a14ea7b4e177d8620514ad4155f20769591a327ec14d73a6ad71f6b146c5ab3f90264b0b28dd11bb1410c54c4b359ceb0ad35a56be295681621a44590efba7",
          "sha256": "47bf95c9676fdfbe67f0520c04dfb51c5c4f5ba2ab4a4fa8200f1694b86e1ff5",
          "sha1": "01b0a081929d040f66e5705b9adb6b43dfa70bf2",
          "md5": "46480d0ae3ae044749b924c7bc87be8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fscript-3.1.2-1.16.5-sources.jar",
          "url": "fscript-3.1.2-1.16.5-sources.jar",
          "size": 44952,
          "sha512": "54d4c1343026a4ce6fee63563de0bffcf066c6e4ac4143b52cec557d6bc0ea3743d37123df8e40386013f41408561e947c910eabf3a455a026a3493ba9932198",
          "sha256": "6d58e9057d91e0a79598090c4b589493ef9f48696b022f7afa91a3e99997719c",
          "sha1": "b52437bbb9faf0933871e3b3750f7456931822d4",
          "md5": "2b78aa6571e4e90b9d147edf385a638d"
        }
      ]
    }
  ]
}
