{
  "formatVersion": "1.1",
  "component": {
    "group": "tf.ssf.sfort",
    "module": "fscript",
    "version": "2.2.0-1.16.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fscript-2.2.0-1.16.5.jar",
          "url": "fscript-2.2.0-1.16.5.jar",
          "size": 100546,
          "sha512": "c25587a5d7e7802f21f176fa8df34b93f8ccd56fddec3c2b3efbfe7d7f3093b119d1a69d5441df8e290065f3cc32c735aa75e825c3e5bca08c09a273afe527ab",
          "sha256": "30080fefdab49eeb50973dce99dc9eb783492b06c77183a42b7d97557331fc52",
          "sha1": "689341a5cae3d94fb677aad84abb3832a8c14809",
          "md5": "f5279cee9a8f4cfdfe8878a9377c0e04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "fscript-2.2.0-1.16.5.jar",
          "url": "fscript-2.2.0-1.16.5.jar",
          "size": 100546,
          "sha512": "c25587a5d7e7802f21f176fa8df34b93f8ccd56fddec3c2b3efbfe7d7f3093b119d1a69d5441df8e290065f3cc32c735aa75e825c3e5bca08c09a273afe527ab",
          "sha256": "30080fefdab49eeb50973dce99dc9eb783492b06c77183a42b7d97557331fc52",
          "sha1": "689341a5cae3d94fb677aad84abb3832a8c14809",
          "md5": "f5279cee9a8f4cfdfe8878a9377c0e04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fscript-2.2.0-1.16.5-sources.jar",
          "url": "fscript-2.2.0-1.16.5-sources.jar",
          "size": 42618,
          "sha512": "5b271a4bd183a9e9906b7ad317c657cb9980383e9519c85e4f399279b90a5f6a5dd8cf048cd575e53f165e9fbde4f2aeb50d817bb84d65cb217410f168222ea3",
          "sha256": "789325945e9fddd1ada5fabe95e2fe98d9c1bdfe49036200e3d641b1a53f25eb",
          "sha1": "3ed2067b73a3256a8f29a569bb7df2a624908ca6",
          "md5": "9a7593ff29ee47199222de27fd9039ed"
        }
      ]
    }
  ]
}
